### ISSUE TITLE
Fullscreen turns off

### ISSUE THREAD

**Issue by souree666** [Xenomer/spicetify-enable-fullscreen#1]
Fullscreen mode goes away once a new song starts playing

I was listening to music on my playlist, with fullscreen mode on and the fullscreen mode turned off once a new song started playing

**Comment by Xenomer** [comment]
What version of Spotify are you using? I'm using a fairly old version (1.0.85.259) and can't currently reproduce the issue. There might be some new cheat-checkers in place on the newer versions I'm not aware of.

**Comment by souree666** [comment]
Hey thanks for the reply, to answer your question, I'm using the latest spotify version 1.1.32.618. I'll try look for a download for the same version as you and I'll keep you updated. 

EDIT: It works fine, even when I skip the songs. You were right about the version. Thank you.
