### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by Mashkiki** [Xenomer/spicetify-enable-fullscreen#5]
So I put the .js file into my Extensions directory, i did enable it but the button still doesn't show up, any help?

**Comment by dinouse** [comment]
yup same here

Spotify for macOS (Intel)
1.1.68.628.geb44bd66
macOS Big Sur

**Comment by Poopooracoocoo** [comment]
It's simply not compatible anymore with the new Spotify and Spicetify, to clear things up.

**Comment by dinouse** [comment]
nahhh use this. got a way round to do that https://github.com/khanhas/spicetify-cli/wiki/Extensions#full-app-display

**Comment by Poopooracoocoo** [comment]
You can now find the above wiki link at https://spicetify.app/docs/advanced-usage/extensions#full-app-display

**Comment by Xenomer** [comment]
I haven't used Spicetify or this extension since I first created it myself, so I should probably deprecate the project as there seems to be a better alternative now anyways.
